### ISSUE TITLE
404 error and no files downloaded for VR menu

### ISSUE THREAD

**Issue by gamemastergit** [leckylao/SpringboardVR-Games-Export-System#1]
Hi there Lecky!  I love that you have come up with this way to use the Springboard game data to create a website menu.  Thank you!  I would be willing to subscribe and use this feature once I can prove that it works.

When I log in and get to the page with EXPORT and hit "next" to let the system create the file for me, it comes back with a 404 error and no files get downloaded...

Any suggestions?
Thank you!
Michael

![Screen Shot 2019-07-05](https://user-images.githubusercontent.com/32916051/60733181-2168e780-9f1a-11e9-88ab-9ce48915036d.png)

**Comment by leckylao** [comment]
Hi Michael,

Thank you for your email and interest. Sorry for the late reply that missed
the notification.

SpringboardVR has upgraded their API to use GraphQL which breaks the
system, as you can see our games list also haven't update for a while
https://vrcorner.com.au/games. Moreover they also changed their whole
database structure and migrated data to a new database.

The current status is I can get the game list export manually through the
new GraphQL. But haven't got time to implement it and I'm going oversea in
August. I'm afraid there would be some delay for the fix. Will keep you
updated.

**Comment by CiscoServerGeek** [comment]
Any update? I think you posted on the Springboard forum that you were working on this.

**Comment by leckylao** [comment]
Yes, just a quick update of the current progress. Integration with the current SpringboardVR system has been done. Now just tweeting the final games page UI then will release the system. Stay Tuned!

**Comment by leckylao** [comment]
Hi @gamemastergit @CiscoServerGeek,

The system has been successfully updated with SpringboardVR's GraphQL API and live now. Please feel free to try out and let me know if any issues. 

https://springboardvr.vrcorner.com.au/
