### ISSUE TITLE
Tags not deleting

### ISSUE THREAD

**Issue by crazevr** [leckylao/SpringboardVR-Games-Export-System#3]
Question lol We deleted Tags on springboard but the export kept them is there a fix for that?

**Comment by leckylao** [comment]
Hi @crazevr ,

patch just pushed. please export again and it should work now.

**Comment by crazevr** [comment]
Your amazing thank you!


Mark Rutherford
Owner
CrazeVR Virtual Tours
info@crazevr.com<mailto:info@crazevr.com>
www.crazevr.com<http://www.crazevr.com>
269-588-1117

[cid:image002.png@01D62312.5A331910]
