### ISSUE TITLE
Some Filters not working

### ISSUE THREAD

**Issue by vrarrival** [leckylao/SpringboardVR-Games-Export-System#4]
Hi Lecky, Hope you are safe and well over your way. A small issue that I found with the latest export. The 'Music and Art' filter didn't work. Had 0 titles showing but doing a search for a title like Synth Riders, it came up fine (including having 'Music and Art' as a filter  above it. All of the other filters look like they are working ok. Only reason I tried Music and Art was to check that Beat Saber had been removed.... Cheers, Andrew Lyttle

**Comment by leckylao** [comment]
Hi @vrarrival ,

Thank you for reporting and it's now fixed!
