### ISSUE TITLE
Log-in error

### ISSUE THREAD

**Issue by vrarrival** [leckylao/SpringboardVR-Games-Export-System#5]
Tried updating the game list but it comes up with an authentication error when I try to update the games list: 
{"errors":[{"message":"403 - Authentication Error: You are not logged in.","extensions":{"statusCode":403,"category":"authentication"},"locations":[{"line":3,"column":13}],"path":["currentOrganization"]},{"message":"403 - Authentication Error: You are not logged in.","extensions":{"statusCode":403,"category":"authentication"},"locations":[{"line":20,"column":13}],"path":["games"]}]}
Going back to SpringboardVR/Admin/Users, there was a part next to the VR-ARRIVAL user details (under edit) where it had that a custom access is not supported and asked me to select between Admin, Manager and Staff. I selected Manager which should have access to the launcher settings but no luck. Any suggestions?
Cheers, Andrew

**Comment by leckylao** [comment]
Just deployed the fix. Closing ticket now. Can reopen if issue still exist.
