### ISSUE TITLE
New Game export webpage not working

### ISSUE THREAD

**Issue by vrarrival** [leckylao/SpringboardVR-Games-Export-System#6]
Hi Lecky - the search output webpage isn't working anymore. Comes up with an error message saying: "The webpage at https://springboardvr.leckylao.com/users/036c4410-f898-11e8-a157-8522c690fb6f/games might be temporarily down or it may have moved permanently to a new web address."
One of the other users on Springboard reported that the SSL certificate had expired for the site. Would love to have this back up and running soon as school holidays are on.
Many thanks.
Cheers, Andrew

**Comment by leckylao** [comment]
Renewed

> One of the other users on Springboard reported that the SSL certificate had expired for the site. Would love to have this back up and running soon as school holidays are on.

Can I ask what's the URL that you see the report? Might also update there.

**Comment by vrarrival** [comment]
Hi Lecky,
Many thanks for fixing that up! I let the user that posted on the SpringboardVR community know and asked if he could send through the URL but all he said was that he isn’t getting the security messages any more and it is all working fine…
Thanks again.
Cheers, Andrew

**Comment by leckylao** [comment]
Sorry. I meant what's the URL for the community again? I haven't check it out for a while. Is it this one?  https://community.springboardvr.com. I think I don't have access to it anymore. Could you post if any issue let them post on the GitHub issue instead of the forum please? Thanks.

**Comment by vrarrival** [comment]
Hi Lecky – no problem. Will let them know.
Cheers, Andrew
